project_id = "fphmujxruswmvlwceodl"

[database]
default_extensions = ["pgcrypto", "uuid-ossp", "pg_net", "pg_cron"]

[[functions]]
name = "clean-shift-history"
verify_jwt = true

[[functions]]
name = "sync-open-shift-to-calendar"
verify_jwt = true

[[functions]]
name = "send-password-reset"
verify_jwt = false

[[functions]]
name = "send-webhook"
verify_jwt = false

[[functions]]
name = "resend-webhook"
verify_jwt = false

[[functions]]
name = "face-verify"
verify_jwt = false

[[functions]]
name = "create-payment"
verify_jwt = true

[[functions]]
name = "send-notification-email"
verify_jwt = false

[[functions]]
name = "send-sms"
verify_jwt = false

[[functions]]
name = "calendar-sync"
verify_jwt = true

[[functions]]
name = "create-checkout"
verify_jwt = true

[[functions]]
name = "check-subscription"
verify_jwt = true

[[functions]]
name = "customer-portal"
verify_jwt = true

[[functions]]
name = "cancel-subscription"
verify_jwt = true

[[functions]]
name = "shifts-api"
verify_jwt = true

[[functions]]
name = "chat-ai-assistant"
verify_jwt = false

[[functions]]
name = "delete-user-account"
verify_jwt = true
