
import { z } from 'zod';

export const employeeFormSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  email: z.string().email('Valid email is required').optional().or(z.literal('')),
  job_title: z.string().min(1, 'Job title is required'),
  department: z.string().min(1, 'Department is required'),
  site: z.string().min(1, 'Site is required'),
  salary: z.number().min(0, 'Salary must be positive'),
  hourly_rate: z.number().min(0, 'Hourly rate must be positive').optional(),
  start_date: z.string().min(1, 'Start date is required'),
  lifecycle: z.enum(['Active', 'Inactive', 'Terminated']),
  status: z.enum(['Active', 'Inactive', 'On Leave']),
  location: z.enum(['Office', 'Remote', 'Hybrid']),
  annual_leave_days: z.number().min(0).max(365),
  sick_leave_days: z.number().min(0).max(365),
  role: z.enum(['employee', 'manager', 'admin', 'hr']),
  shift_pattern_id: z.string().optional(),
  monday_shift_id: z.string().optional(),
  tuesday_shift_id: z.string().optional(),
  wednesday_shift_id: z.string().optional(),
  thursday_shift_id: z.string().optional(),
  friday_shift_id: z.string().optional(),
  saturday_shift_id: z.string().optional(),
  sunday_shift_id: z.string().optional(),
  // Weekly availability fields
  monday_available: z.boolean().optional(),
  monday_start_time: z.string().optional(),
  monday_end_time: z.string().optional(),
  tuesday_available: z.boolean().optional(),
  tuesday_start_time: z.string().optional(),
  tuesday_end_time: z.string().optional(),
  wednesday_available: z.boolean().optional(),
  wednesday_start_time: z.string().optional(),
  wednesday_end_time: z.string().optional(),
  thursday_available: z.boolean().optional(),
  thursday_start_time: z.string().optional(),
  thursday_end_time: z.string().optional(),
  friday_available: z.boolean().optional(),
  friday_start_time: z.string().optional(),
  friday_end_time: z.string().optional(),
  saturday_available: z.boolean().optional(),
  saturday_start_time: z.string().optional(),
  saturday_end_time: z.string().optional(),
  sunday_available: z.boolean().optional(),
  sunday_start_time: z.string().optional(),
  sunday_end_time: z.string().optional(),
});

export type EmployeeFormValues = z.infer<typeof employeeFormSchema>;
